version: '3.7'
services:
  Wago-CAA-Runtime:
    image: wagoalex/cc-fw27:latest
    container_name: "dat--wago"
    command: "--init"
    network_mode: host
    privileged: true
    volumes:
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - /tmp:/tmp
      - /drm:/drm
      - ./configs/${PORTAINER_EDGE_ID}:/${PORTAINER_EDGE_ID}
    restart: always
