version: '3.7'
services:
  Wago-CAA-Runtime:
    image: geekychebbi/cc100-codesys:latest
    container_name: "050---wago-caa3-cc-FW27"
    command: "--init"
    network_mode: host
    privileged: true
    volumes:
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - /tmp:/tmp
      - /drm:/drm
      - ./configs/5e18e002-f4f9-4fdc-a114-0ac0ca61b299:/home/codesys_root/PlcLogic/Application
    restart: always
